### ISSUE TITLE
Bug on sample: left a gap...

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [krossovochkin/Android-SwipeToDismiss-RecyclerView#4]
Done some serious swiping , and got to this (on the Lollipop emulator) .

![untitled20150113002716](https://cloud.githubusercontent.com/assets/5357526/5712420/f4bf088a-9aba-11e4-951a-116c7591a7bd.png)

EDIT: I've succeeded doing it on a real device too, and if I use GridLayoutManager, I can even reach 2 gaps (not sure if it has anything to do with it) :

![device-2015-01-13-003816](https://cloud.githubusercontent.com/assets/5357526/5712608/871f3622-9abc-11e4-9ef7-5f22a1f62c50.png)

**Comment by jtexp** [comment]
Implemented this on my code and added the ability to create new items.  Every deleted item will hide new items until you add more items than you've deleted.  To remedy this I removed 

```
// TODO: this is temp solution for preventing blinking item onDismiss
//llm.findViewByPosition(position).setVisibility(View.GONE);
```

Of course this brings back the blinking item onDismiss but that's better than what was happening before.  I'm going to work on some other parts of my app and keep checking in here for solutions.

**Comment by krossovochkin** [comment]
OK, thanks for your feedback. The situation is follows
I think found the cause of the problem. There are two different onDismiss animations: the first is the built-in original library onDismiss animation, and the second one is animation from `mAdapter.notifyItemRemoved()`.
So these gaps (and also blinking) appear because of conflicts of these animations, I think.
I thought, that in this case the best (of course temp) solution is not to use `notifyItemRemoved` and use only `notifyDataSetChange`. In this case there will be no beautiful animations w/ GridLayoutManager, but this solution is more stable.
Later on I will think about how to properly remove original library's built-in onDismiss animation and use only animation provided by RecyclerView and other components
