### ISSUE TITLE
item background selector

### ISSUE THREAD

**Issue by johnfrey99** [krossovochkin/Android-SwipeToDismiss-RecyclerView#6]
I've been trying to use this example however I noticed that in setting the background of the item view to a drawable selector doesn't fire the selected state as it normally would. 

For example updating the code to the following doesn't work... 
`
mAdapter = new RecyclerView.Adapter<CustomViewHolder>() {
    @Override
    public CustomViewHolder onCreateViewHolder(ViewGroup viewGroup, int i) {
        View view = LayoutInflater.from(viewGroup.getContext()).inflate(
                android.R.layout.simple_list_item_1, viewGroup, false);
        view.setBackgroundResource(android.R.drawable.list_selector_background);
        view.setClickable(true);
        return new CustomViewHolder(view);
    }
....
`

However if I remove the recyclerview touchListener and onItemTouchListener it works ok. Any ideas on what could be wrong or how to  implement a background selector on item views when combined with the swipe/dismiss touch listener and item click listener?

**Comment by krossovochkin** [comment]
I tried to do something with this issue.
_Disclaimer_: I don't think that I found the good clear solution for the issue. Also there might be some mistakes in what I did. So, if somebody finds something interesting, you're welcome.

Next, I will explain my thoughts and what I did.

First of all, problem with background selectors is not the problem of swipe-to-dismiss logic.
The problem is that you can't set views clickable (or set clicklisteners for them in `onCreateViewHolder`), because in this case these listeners will intercept all the click events and touchListener for swipe-to-dismiss will not receive any events and will not work.
That is why I used for onItemTouchClick events separate `RecyclerVIew.OnItemTouchListener` and added it to recycler view with `mRecyclerView.addOnItemTouchListener(...)`.

So, I thought that the best thing I can do to resolve issue with background resources is to develop this listener.
What I would like to have as a result:
1) When item is pressed it should highlight it
2) But when recycler view is scrolled, first touch on item should not highlight it
3) Item should be highlighted on long click
4) When item is clicked it should be highlighted and this highlight should disappear after some delay

So, item should be highlighted in two cases:
1) in GestureDetector.onShowPress
2) in GestureDetector.onSingleTapUp

Hightlight should be removed in:
1) GestureDetector.onSingleTapUp after some delay after item was highlighted
2) RecyclerView.OnItemTouchListener.onInterceptTouchEvent if this is ACTION_UP event
3) RecyclerView.Adapter.onBindViewHolder (I explain this below)

Why we need point 3): recycler view reuses child views. So if you click first item and then scroll down, you will see some element below is highlighted too.
So, you should 'reset' item press state in onBindViewHolder.

Hope it helps.

PS: I pushed the solution to the develop branch, cause I'm not sure that this is the true solution.
Please, check it and tell what do you think about it.

**Comment by johnfrey99** [comment]
Thanks I really appreciate you trying to fix this. I haven't had a chance yet to see how your solution works but I'll be sure to let you know.
